### ISSUE TITLE
After updating the app stays blank when opening it

### ISSUE THREAD

**Issue by Hamzabdx** [lich4/ChargeLimiter#75] opened 2024-07-20 10:33 UTC
I updated from version 1.6.0 to 1.6.1 on dopamine ios 16.2 iphone 14 pm and when i open the app it stays blank uninstaling and reinstalling doesnt fix it even downgrading doesnt fix it the only thing that works now is trollstore version

**Comment by lich4** [comment] 2024-07-20 10:50
It's caused by some tweaks probably, these tweaks will hook into com.apple.UIKit

**Comment by Hamzabdx** [comment] 2024-07-21 12:01
I dont think so i blocked all tweaks to the apps using choicy also why downgrading it doesnt work either it used to work fine but since this last update it ruined something now even downgrading to the version that used to work doesnt fix it

**Comment by lich4** [comment] 2024-07-21 12:18
You can try downgrade to last working version, . If it still not work, then it definitely caused by some tweak.

**Comment by Hamzabdx** [comment] 2024-07-31 11:09
Btw the only fix i found for this is reinstalling the tweak while in safemode but i dont have this problem with any other tweak and it keeps happening and i keep having to go into safemode and reinstalling it

**Comment by lich4** [comment] 2024-08-02 11:22
> Btw the only fix i found for this is reinstalling the tweak while in safemode but i dont have this problem with any other tweak and it keeps happening and i keep having to go into safemode and reinstalling it

If your jailbreak environment is pure enough, there will be no stuck.
It is just caused by some bad/ill tweaks, whatever, it will be fix in the future with a standalone daemon, currently the executable act as both application and daemon

**Comment by lich4** [comment] 2024-10-17 13:50
Fixed in v1.7

**Closed by lich4** 2024-10-17 13:50 UTC
